// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5CLErll2nryXc5YKps-O7Dzf-b5I9eHI',
    appId: '1:1001058338541:web:8eb2ef1a542e3d4f72aee4',
    messagingSenderId: '1001058338541',
    projectId: 'rasoi-e8da9',
    authDomain: 'rasoi-e8da9.firebaseapp.com',
    storageBucket: 'rasoi-e8da9.firebasestorage.app',
    measurementId: 'G-7LW4CEGHLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEP0qnTY_BLDfAUeTqioooUyjzcM-YEY',
    appId: '1:1001058338541:android:ae807fb5cc5d364072aee4',
    messagingSenderId: '1001058338541',
    projectId: 'rasoi-e8da9',
    storageBucket: 'rasoi-e8da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBngi7-tvFxydt6IuvE0dv_7CrMpwZMZeA',
    appId: '1:1001058338541:ios:673292e57475335d72aee4',
    messagingSenderId: '1001058338541',
    projectId: 'rasoi-e8da9',
    storageBucket: 'rasoi-e8da9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBngi7-tvFxydt6IuvE0dv_7CrMpwZMZeA',
    appId: '1:1001058338541:ios:673292e57475335d72aee4',
    messagingSenderId: '1001058338541',
    projectId: 'rasoi-e8da9',
    storageBucket: 'rasoi-e8da9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5CLErll2nryXc5YKps-O7Dzf-b5I9eHI',
    appId: '1:1001058338541:web:ead25d8b4f32b3ce72aee4',
    messagingSenderId: '1001058338541',
    projectId: 'rasoi-e8da9',
    authDomain: 'rasoi-e8da9.firebaseapp.com',
    storageBucket: 'rasoi-e8da9.firebasestorage.app',
    measurementId: 'G-BQC973YVHQ',
  );
}
